### PR TITLE
fix: notify when purge cache completed

### LINKED ISSUE #16: Purge caches async method lacks completion notification
In the current implementation of the image downloader, the `purgeCache` method does not provide a way to notify the caller when the cache clearing process is completed. This can lead to issues in cases where the user needs to perform an action immediately after the cache has been cleared, mainly testing

### PR DESCRIPTION
**Pull request by albertocsouto**
Resolves #16

### CODE REVIEW

File: Tests/NMAImageFetchTests/NMAImageFetchTests.swift [hunk 1]
```diff
@@ -5,8 +5,8 @@ import UIKit
 
 final class NMAImageFetchTests: XCTestCase {
 
-    override class func setUp() {
-        ImageFetch().purgeCaches()
+    override func setUp() async throws {
+        await ImageFetch().purgeCaches()
```
Comment (albertocsouto) [inline Tests/NMAImageFetchTests/NMAImageFetchTests.swift:9]: Nice out of the box wrapper :)

**Review by bobergj — APPROVED** [review]
Nice
